### ISSUE TITLE
Cadence of npm publishing

### ISSUE THREAD

**Issue by atifsyedali** [httptoolkit/openapi-directory-js#9]
Any plans of maintaining a cadence for publishing to npm?

**Comment by pimterry** [comment]
Absolutely! Haven't published it for a while, but honestly I didn't realise anybody else was using it! :smile:. I've just pushed an update now, let me know if it works for you.

Out of interest, what are you using this for?

I'll try to look at automating publishing for this soon. For the moment I've set up a daily automated build to check everything still builds so that publishing is easy, and I'll try to do so regularly, but do feel free to ping here any time if there's an update that's not published that you need.

**Comment by atifsyedali** [comment]
Thanks @pimterry! I am currently exploring this for adding integrations into our project.

**Comment by pimterry** [comment]
Took quite a while, but this is now fixed! The directory autopublishes to npm every month (https://github.com/httptoolkit/openapi-directory-js/blob/main/.github/workflows/npm-publish.yml)
